name: cloud_car
description: A new Flutter project.
publish_to: 'none'


version: 1.0.26+27

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4

  #国际化支持
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  permission_handler: 9.2.0
  #包信息
  package_info_plus: ^1.4.2
  #状态管理
  provider: ^6.0.2
  #屏幕适配
  flutter_screenutil: 5.4.0+1
  #常用工具类
  flustars: ^2.0.1
  #弹窗
  bot_toast: ^4.0.1
  #http
  dio: ^4.0.0
  #路由相关
  get: ^4.1.4
  #本地化存储
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  #刷新组件
  flutter_easyrefresh: ^2.2.1
  extended_image: ^7.0.0-dev.1
  #下拉框
  gzx_dropdown_menu: ^3.1.0
  #各种扩展
  velocity_x: ^3.0.0
  #列表选择器
  azlistview: ^2.0.0
  github_language_colors:
    git:
      url: https://github.com/meng-fucius/github_language_colors.git
  # 汉字转拼音
  lpinyin: ^2.0.0
  #轮播
  flutter_swiper_tv: ^1.1.6-nullsafety
  #角标
  badges: ^2.0.2
  #手写
  signature: ^5.0.0
  # 相机
  image_picker: ^0.8.5
  # 虚线框
  dotted_border: ^2.0.0+2
  # 时间轴
#  timelines: ^0.1.0
  #日志输出
  power_logger: ^1.2.2
  #极光认证
#  jverify: 2.2.5
  #极光推送
#  jpush_flutter: ^2.3.4
  #微信登录及支付
#  fluwx: ^3.12.0
  fluwx: ^3.8.3
  #支付宝支付
  tobias: ^2.4.0+2
  #widget转image
  screenshot: ^1.2.3
  #保存图片
  image_gallery_saver: ^1.7.1
  #生成二维码
  barcode_widget: ^2.0.2
  #json model生成注解
  json_annotation: ^4.4.0

  #拨号
  url_launcher: 6.1.0
  #生成类重载==运算符和toString方法
  equatable: ^2.0.3
  #设备平台信息
  platform: ^3.1.0
  #路径
  path_provider: ^2.0.9
  #工具类
  common_utils: ^2.1.0
  #日历组件
  table_calendar: ^3.0.6
  #地图组件
  map_launcher: ^2.2.3
  # 精度丢失
  decimal: ^2.2.0
  # 图片压缩
  flutter_image_compress: ^1.0.0-nullsafety
  #苹果登录
  sign_in_with_apple: ^4.1.0
  #websocket
  web_socket_channel: 2.2.0
  #webView
  flutter_inappwebview: 5.4.3
  #图片缓存
  cached_network_image: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  #导入包整理
  import_sorter: ^4.5.1
  hive_generator: ^1.1.0
  #脚本工具
  grinder: ^0.9.2
  flutter_native_splash: ^1.1.8+4
  #model自动生成
  json_serializable: ^6.1.3
  build_runner: ^2.0.2
  yaml: ^3.1.0
  pub_semver: ^2.0.0
  flutter_gen_runner: ^4.1.3
  flutter_lints: ^2.0.0
  path: ^1.8.1


flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/data/
