name: cloud_car
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #国际化支持
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  permission_handler: ^9.2.0
  #包信息
  package_info: ^2.0.0
  #状态管理
  provider: ^5.0.0
  #屏幕适配
  flutter_screenutil: ^5.0.0+2
  #常用工具类
  flustars: ^2.0.1
  #弹窗
  bot_toast: ^4.0.1
  #http
  dio: ^4.0.0
  #路由相关
  get: ^4.1.4
  #本地化存储
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  #刷新组件
  flutter_easyrefresh: ^2.2.1

  extended_image: ^3.0.0

  #列表选择器
  azlistview: ^2.0.0

  # 汉字转拼音
  lpinyin: ^2.0.0

  github_language_colors:
    git:
      url: git://github.com/Sky24n/github_language_colors.git



dev_dependencies:
  flutter_test:
    sdk: flutter
  #导入包整理
  import_sorter: ^4.5.1
  hive_generator: ^1.1.0
  #脚本工具
  grinder: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  #model自动生成
  json_serializable: ^6.1.3
  build_runner: ^2.0.2
  yaml: ^3.1.0
  pub_semver: ^2.0.0
  flutter_gen_runner: ^4.1.3
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/data/